// Add C includes here
#include <ctype.h>
#include <math.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#if defined __cplusplus
// Add C++ includes here
#include <QAbstractItemModel>
#include <QAbstractProxyModel>
#include <QAction>
#include <QApplication>
#include <QBrush>
#include <QBuffer>
#include <QByteArray>
#include <QCheckBox>
#include <QClipboard>
#include <QCloseEvent>
#include <QColor>
#include <QColorDialog>
#include <QComboBox>
#include <QCompleter>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDataStream>
#include <QDataWidgetMapper>
#include <QDate>
#include <QDateEdit>
#include <QDateTime>
#include <QDateTimeEdit>
#include <QDebug>
#include <QDesktopServices>
#include <QDesktopWidget>
#include <QDialog>
#include <QDir>
#include <QDockWidget>
#include <QDomComment>
#include <QDomElement>
#include <QDoubleSpinBox>
#include <QDrag>
#include <QEvent>
#include <QEventLoop>
#include <QExplicitlySharedDataPointer>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFileSystemWatcher>
#include <QFocusEvent>
#include <QFont>
#include <QFontComboBox>
#include <QFontDialog>
#include <QFrame>
#include <QGraphicsItem>
#include <QGraphicsScene>
#include <QGraphicsSceneMouseEvent>
#include <QGraphicsTextItem>
#include <QGraphicsView>
#include <QHBoxLayout>
#include <QHash>
#include <QHeaderView>
#include <QIODevice>
#include <QIcon>
#include <QIdentityProxyModel>
#include <QImage>
#include <QInputDialog>
#include <QItemDelegate>
#include <QKeyEvent>
#include <QLabel>
#include <QLineEdit>
#include <QList>
#include <QLocale>
#include <QMainWindow>
#include <QMap>
#include <QMapIterator>
#include <QMenu>
#include <QMenuBar>
#include <QMessageBox>
#include <QMetaObject>
#include <QMetaProperty>
#include <QMetaType>
#include <QMimeData>
#include <QMouseEvent>
#include <QMutex>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QObject>
#include <QPaintEvent>
#include <QPainter>
#include <QPair>
#include <QPalette>
#include <QPixmap>
#include <QPoint>
#include <QPointF>
#include <QPrintDialog>
#include <QPrinter>
#include <QProgressDialog>
#include <QPushButton>
#include <QRect>
#include <QRectF>
#include <QRegExp>
#include <QRegularExpression>
#include <QResource>
#include <QScopedPointer>
#include <QScriptEngine>
#include <QScriptValueIterator>
#include <QScriptable>
#include <QScrollBar>
#include <QSet>
#include <QSettings>
#include <QSharedData>
#include <QSharedPointer>
#include <QShortcut>
#include <QSignalMapper>
#include <QSize>
#include <QSortFilterProxyModel>
#include <QSpinBox>
#include <QSqlDatabase>
#include <QSqlDriver>
#include <QSqlError>
#include <QSqlQuery>
#include <QSqlQueryModel>
#include <QSqlRecord>
#include <QSqlRelationalTableModel>
#include <QSsl>
#include <QSslConfiguration>
#include <QSslError>
#include <QStandardItemModel>
#include <QStatusBar>
#include <QString>
#include <QStringList>
#include <QStringListModel>
#include <QStyle>
#include <QStyleOptionGraphicsItem>
#include <QStylePainter>
#include <QStyledItemDelegate>
#include <QTabWidget>
#include <QTableView>
#include <QTcpSocket>
#include <QTextDocument>
#include <QTextEdit>
#include <QTextFragment>
#include <QTextLayout>
#include <QTextStream>
#include <QTimer>
#include <QToolBar>
#include <QToolButton>
#include <QTreeView>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QUiLoader>
#include <QUrl>
#include <QVBoxLayout>
#include <QVariant>
#include <QVector>
#include <QWidget>
#include <QXmlStreamReader>
#include <QXmlStreamWriter>
#include <QtGlobal>
#include <QtGui>
#include <QtMath>
#include <QtXml>
#include <algorithm>
#include <cstdlib>
#include <limits>
#include <math.h>
#include <memory>
#include <optional>
#include <private/qzipreader_p.h>
#include <private/qzipwriter_p.h>
#include <stdexcept>
#endif
