-- Apply the 'SEPARADO' logística status to the status-aware VIEWs on the LIVE
-- database. Run once against the live `staccato` DB.
--
-- SEPARADO marks sold stock that has been physically picked/separated but is
-- still on hand (reserved). It must be treated exactly like 'ESTOQUE' anywhere
-- a view reports "in stock / in the warehouse". Views are CREATE OR REPLACE
-- (idempotent); no data backfill is required.
--
-- Companion to db/separado_status_procedures.sql (the cascade procedures
-- already handle SEPARADO). The four view bodies below are kept in sync with
-- initdb.sql.
--
--   view_galpao          -- include SEPARADO so separated items still show in the warehouse layout
--   view_entrega         -- count SEPARADO under `Estoque` (not `Outros`) for the Entregues filters
--   view_calendario      -- exclude SEPARADO (like ESTOQUE) from the logística delivery calendar
--   view_entrega_pendente-- kept consistent; the app uses the dynamic Sql::view_entrega_pendente(), not this view

USE `staccato`;

-- -----------------------------------------------------
-- view_galpao  (separated items must remain in the warehouse layout)
-- -----------------------------------------------------
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `staccato`.`view_galpao` AS select `ehc`.`idConsumo` AS `idEstoque_idConsumo`,`ehc`.`idEstoque` AS `idEstoque`,`ehc`.`descricao` AS `descricao`,`p`.`formComercial` AS `formComercial`,`e`.`status` AS `status`,`vp2`.`idVenda` AS `idVenda`,`ehc`.`codComercial` AS `codComercial`,`n`.`numeroNFe` AS `numeroNFe`,`n`.`idNFe` AS `idNFe`,`ehc`.`caixas` AS `caixas`,`ehc`.`quant` AS `quant`,`ehc`.`idBloco` AS `idBloco`,`ehc`.`idVendaProduto2` AS `idVendaProduto2`,`e`.`lote` AS `lote`,'CLIENTE' AS `tipo` from ((((`staccato`.`estoque_has_consumo` `ehc` left join `staccato`.`estoque` `e` on((`ehc`.`idEstoque` = `e`.`idEstoque`))) left join `staccato`.`nfe` `n` on((`e`.`idNFe` = `n`.`idNFe`))) left join `staccato`.`venda_has_produto2` `vp2` on((`ehc`.`idVendaProduto2` = `vp2`.`idVendaProduto2`))) left join `staccato`.`produto` `p` on((`ehc`.`idProduto` = `p`.`idProduto`))) where (`vp2`.`status` in ('ESTOQUE','SEPARADO','EM COLETA','EM RECEBIMENTO','ENTREGA AGEND.','EM ENTREGA')) union select `e`.`idEstoque` AS `idEstoque_idConsumo`,`e`.`idEstoque` AS `idEstoque`,`e`.`descricao` AS `descricao`,`p`.`formComercial` AS `formComercial`,`e`.`status` AS `status`,NULL AS `idVenda`,`e`.`codComercial` AS `codComercial`,`n`.`numeroNFe` AS `numeroNFe`,`n`.`idNFe` AS `idNFe`,(`e`.`restante` / `p`.`quantCaixa`) AS `caixas`,`e`.`restante` AS `quant`,`e`.`idBloco` AS `idBloco`,NULL AS `idVendaProduto2`,`e`.`lote` AS `lote`,'EST. LOJA' AS `tipo` from ((`staccato`.`estoque` `e` left join `staccato`.`nfe` `n` on((`e`.`idNFe` = `n`.`idNFe`))) left join `staccato`.`produto` `p` on((`e`.`idProduto` = `p`.`idProduto`))) where ((`e`.`restante` > 0) and (`e`.`status` <> 'cancelado'));

-- -----------------------------------------------------
-- view_entrega  (Entregues screen: SEPARADO counts as Estoque, not Outros)
-- -----------------------------------------------------
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `staccato`.`view_entrega` AS select cast(min((`v`.`data` + interval `v`.`prazoEntrega` day)) as date) AS `prazoEntrega`,`vp2`.`idVenda` AS `idVenda`,group_concat(distinct `vp2`.`recebeu` separator ',') AS `Recebeu`,group_concat(distinct `vp2`.`entregou` separator ',') AS `Entregou`,sum((`vp2`.`status` in ('ESTOQUE','SEPARADO'))) AS `Estoque`,sum((`vp2`.`status` = 'ENTREGUE')) AS `Entregue`,sum(((`vp2`.`status` not in ('ESTOQUE','SEPARADO')) and (`vp2`.`status` <> 'ENTREGUE'))) AS `Outros`,`che`.`bairro` AS `Bairro`,`che`.`logradouro` AS `Logradouro`,`che`.`numero` AS `Número`,`che`.`cidade` AS `Cidade` from ((`staccato`.`venda_has_produto2` `vp2` left join `staccato`.`venda` `v` on((`vp2`.`idVenda` = `v`.`idVenda`))) left join `staccato`.`cliente_has_endereco` `che` on((`v`.`idEnderecoEntrega` = `che`.`idEndereco`))) where (not((`vp2`.`idVenda` like '%D'))) group by `vp2`.`idVenda`;

-- -----------------------------------------------------
-- view_calendario  (separated items are not yet shipped -> excluded like ESTOQUE)
-- -----------------------------------------------------
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `staccato`.`view_calendario` AS select concat(`lhe`.`logradouro`,', ',`lhe`.`numero`,', ',`lhe`.`cidade`,', ',`lhe`.`uf`) AS `origem`,concat(`che`.`logradouro`,', ',`che`.`numero`,', ',`che`.`cidade`,', ',`che`.`uf`) AS `destino`,`vp`.`idVenda` AS `idVenda`,`vp`.`idEvento` AS `carga`,sum(`vp`.`caixas`) AS `caixas`,sum(`vp`.`kg`) AS `kg`,`vp`.`data` AS `data`,`t`.`razaoSocial` AS `razaoSocial`,`thv`.`modelo` AS `modelo`,`vp`.`status` AS `status`,`che`.`logradouro` AS `logradouro`,`che`.`numero` AS `numero`,`che`.`bairro` AS `bairro`,`che`.`cidade` AS `cidade`,`che`.`uf` AS `uf`,group_concat(concat(left(`vp`.`produto`,25),' - ',`vp`.`caixas`,' cx.') separator '/') AS `produtos` from (((((`staccato`.`veiculo_has_produto` `vp` left join `staccato`.`transportadora_has_veiculo` `thv` on((`vp`.`idVeiculo` = `thv`.`idVeiculo`))) left join `staccato`.`transportadora` `t` on((`t`.`idTransportadora` = `thv`.`idTransportadora`))) left join `staccato`.`venda` `v` on((`v`.`idVenda` = `vp`.`idVenda`))) left join `staccato`.`cliente_has_endereco` `che` on((`che`.`idEndereco` = `v`.`idEnderecoEntrega`))) left join (select `staccato`.`loja_has_endereco`.`idEndereco` AS `idEndereco`,`staccato`.`loja_has_endereco`.`idLoja` AS `idLoja`,`staccato`.`loja_has_endereco`.`descricao` AS `descricao`,`staccato`.`loja_has_endereco`.`cep` AS `cep`,`staccato`.`loja_has_endereco`.`logradouro` AS `logradouro`,`staccato`.`loja_has_endereco`.`numero` AS `numero`,`staccato`.`loja_has_endereco`.`complemento` AS `complemento`,`staccato`.`loja_has_endereco`.`bairro` AS `bairro`,`staccato`.`loja_has_endereco`.`cidade` AS `cidade`,`staccato`.`loja_has_endereco`.`uf` AS `uf`,`staccato`.`loja_has_endereco`.`codUF` AS `codUF`,`staccato`.`loja_has_endereco`.`desativado` AS `desativado`,`staccato`.`loja_has_endereco`.`created` AS `created`,`staccato`.`loja_has_endereco`.`lastUpdated` AS `lastUpdated` from `staccato`.`loja_has_endereco` where ((`staccato`.`loja_has_endereco`.`idLoja` = 6) and (`staccato`.`loja_has_endereco`.`desativado` = false)) limit 1) `lhe` on((`lhe`.`idLoja` = 6))) where (`vp`.`status` not in ('ESTOQUE','SEPARADO')) group by `vp`.`idVeiculo`,`vp`.`data`,`vp`.`idVenda`,`vp`.`status`,`vp`.`idEvento` order by `vp`.`data`,`vp`.`idVenda`,`t`.`razaoSocial`,`thv`.`modelo`;

-- -----------------------------------------------------
-- view_entrega_pendente  (kept consistent with initdb.sql; not queried by the app)
-- -----------------------------------------------------
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `staccato`.`view_entrega_pendente` AS select `v`.`data` AS `data`,cast((`v`.`data` + interval `v`.`prazoEntrega` day) as date) AS `prazoEntrega`,cast((`v`.`data` + interval `v`.`novoPrazoEntrega` day) as date) AS `novoPrazoEntrega`,cast(min(`vp2`.`dataRealReceb`) as date) AS `dataRealReceb`,`v`.`statusFinanceiro` AS `statusFinanceiro`,`vp2`.`idVenda` AS `idVenda`,sum((`vp2`.`status` in ('ESTOQUE','SEPARADO'))) AS `Estoque`,sum((`vp2`.`status` in ('ENTREGUE','EM ENTREGA','ENTREGA AGEND.'))) AS `Agend/Entregue`,sum((`vp2`.`status` not in ('ESTOQUE','SEPARADO','ENTREGUE','EM ENTREGA','ENTREGA AGEND.','DEVOLVIDO','QUEBRADO'))) AS `Outros`,`che`.`bairro` AS `Bairro`,`che`.`logradouro` AS `Logradouro`,`che`.`numero` AS `Número`,`che`.`cidade` AS `Cidade` from ((`staccato`.`venda_has_produto2` `vp2` left join `staccato`.`venda` `v` on((`vp2`.`idVenda` = `v`.`idVenda`))) left join `staccato`.`cliente_has_endereco` `che` on((`v`.`idEnderecoEntrega` = `che`.`idEndereco`))) where ((not((`vp2`.`idVenda` like '%D'))) and (`v`.`status` not in ('ENTREGUE','CANCELADO','DEVOLVIDO')) and (`v`.`representacao` = false) and (`v`.`devolucao` = false)) group by `vp2`.`idVenda`;
